FROM python:3.13

# Set work directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your project files
COPY . .

# Create a non-root user for running the app
RUN useradd -m django
RUN chown -R django:django /app

# Switch to the non-root user
USER django

# Set the default command for Django (using daphne)
CMD ["daphne", "-b", "0.0.0.0", "-p", "8080", "bucosa.asgi:application"]
