FROM python:3.13

# Set work directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your project files
COPY . .

# Create a non-root user for running the app
RUN useradd -m celeryuser
RUN chown -R celeryuser:celeryuser /app

# Switch to the non-root user
USER celeryuser

# Set the default command for Celery worker
CMD ["celery", "-A", "bucosa", "worker", "--loglevel=info"]
