# Generated by Django 5.2.3 on 2025-06-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='is_verified',
        ),
    ]
