# Generated by Django 5.2.3 on 2025-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
