# Generated by Django 5.2.3 on 2025-06-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_pics/'),
        ),
    ]
