# Generated by Django 5.2.3 on 2025-07-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/'),
        ),
    ]
