# Generated by Django 5.2.3 on 2025-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_profile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
