# Generated by Django 5.2.3 on 2025-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_profile_latitude_user_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
