# Generated by Django 5.2.3 on 2025-07-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
