# Generated by Django 5.2.3 on 2025-07-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='FCM device token for push notifications', max_length=255, null=True),
        ),
    ]
