# Generated by Django 5.2.4 on 2025-08-02 13:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_profile_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size={600}, upload_to='group_pics/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size={600}, upload_to='profile_covers/'),
        ),
    ]
