# Generated by Django 5.2.4 on 2025-08-02 14:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_groupprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='group_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_covers'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pics'),
        ),
    ]
