# Generated by Django 5.2.4 on 2025-08-04 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0022_alter_groupprofile_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmessagereaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmessagereaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='groupmessagereaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='admins',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_following',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='website',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='groupprofile',
            index=models.Index(fields=['creator'], name='users_group_creator_0b63d8_idx'),
        ),
        migrations.AddIndex(
            model_name='user_following',
            index=models.Index(fields=['-created_at'], name='users_user__created_fe4b27_idx'),
        ),
        migrations.AddIndex(
            model_name='user_following',
            index=models.Index(fields=['user', 'following_user'], name='users_user__user_id_02f479_idx'),
        ),
        migrations.AddIndex(
            model_name='user_profile',
            index=models.Index(fields=['privacy'], name='users_user__privacy_aba437_idx'),
        ),
        migrations.AddIndex(
            model_name='user_profile',
            index=models.Index(fields=['date_joined'], name='users_user__date_jo_72a574_idx'),
        ),
        migrations.DeleteModel(
            name='GroupMessageReaction',
        ),
    ]
