# Generated by Django 5.2.4 on 2025-08-25 16:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_groupmessage_file_alter_privatemessage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff_messages',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='staff_messages',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_messages',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='staff_message_images/'),
        ),
        migrations.AlterField(
            model_name='staff_messages',
            name='recipients',
            field=models.ManyToManyField(related_name='received_staff_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff_messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_staff_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
