# Generated by Django 5.2.3 on 2025-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bucosa_menbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Nationality', models.CharField(max_length=150)),
                ('profile', models.ImageField(upload_to='government')),
            ],
        ),
    ]
