# Generated by Django 5.2.3 on 2025-07-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_bucosajoinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bucosa_menbers',
        ),
    ]
