# Generated by Django 5.2.3 on 2025-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0004_currentgovernment_pastgovernment_governmentmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastgovernment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='government_images/'),
        ),
    ]
