# Generated by Django 5.2.3 on 2025-07-10 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_pastgovernment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastGovernmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='government.pastgovernment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
