# Generated by Django 5.2.4 on 2025-08-02 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0006_pastgovernmentmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgovernment',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='government_images/'),
        ),
        migrations.AlterField(
            model_name='pastgovernment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='government_images/'),
        ),
    ]
