# Generated by Django 5.2.4 on 2025-08-02 13:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_event_registered_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size={600}, upload_to='event_covers/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size={600}, upload_to='post_images/'),
        ),
    ]
