# Generated by Django 5.2.4 on 2025-08-02 14:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_event_cover_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_covers'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_images'),
        ),
    ]
