# Generated by Django 5.2.4 on 2025-08-04 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_event_cover_image_alter_post_image'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends Only'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='repost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='activities__post_id_157c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='activities__author__922803_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='activities__start_t_fab7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['group', 'start_time'], name='activities__group_i_735cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'created_at'], name='activities__post_id_1d7f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'created_at'], name='activities__user_id_1cb484_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='activities__author__000c16_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', 'created_at'], name='activities__group_i_8d88a0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['privacy', 'created_at'], name='activities__privacy_e96c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['post', 'created_at'], name='activities__post_id_700332_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['user', 'created_at'], name='activities__user_id_ecc8af_idx'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['post', 'created_at'], name='activities__post_id_f79da0_idx'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['user', 'created_at'], name='activities__user_id_b593a3_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['post', 'created_at'], name='activities__post_id_df9c56_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['user', 'created_at'], name='activities__user_id_3f695e_idx'),
        ),
    ]
