# Generated by Django 5.2.4 on 2025-08-13 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_announcement'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_welcome_post',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_welcome_post', 'created_at'], name='activities__is_welc_f7bce4_idx'),
        ),
    ]
