# Generated by Django 5.2.4 on 2025-08-20 13:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='announcement_images'),
        ),
    ]
