# Generated by Django 5.2.3 on 2025-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('payment_method', models.CharField(max_length=50)),
                ('mobile_money_number', models.CharField(blank=True, max_length=13, null=True)),
                ('time_send', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fellowship_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(upload_to='media/fellowship')),
                ('back_image', models.ImageField(upload_to='media/felloship/back_images')),
            ],
        ),
    ]
