# Generated by Django 5.2.3 on 2025-07-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship_edit',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/felloship/back_images'),
        ),
        migrations.AlterField(
            model_name='fellowship_edit',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/fellowship'),
        ),
    ]
