# Generated by Django 5.2.3 on 2025-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0002_alter_fellowship_edit_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship_edit',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='back_images'),
        ),
        migrations.AlterField(
            model_name='fellowship_edit',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='fellowship/'),
        ),
    ]
