# Generated by Django 5.2.3 on 2025-07-07 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0003_alter_fellowship_edit_back_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowship_edit',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_fellowships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FellowshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='fellowship_event_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fellowship.fellowship_edit')),
            ],
        ),
        migrations.CreateModel(
            name='FellowshipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fellowship_post_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='fellowship_post_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fellowship.fellowship_edit')),
            ],
        ),
        migrations.CreateModel(
            name='FellowshipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fellowship.fellowship_edit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowship_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fellowship', 'user')},
            },
        ),
    ]
