# Generated by Django 5.2.3 on 2025-07-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0004_fellowship_edit_admin_fellowshipevent_fellowshippost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
