# Generated by Django 5.2.4 on 2025-08-02 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0005_alter_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship_edit',
            name='back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='back_images'),
        ),
        migrations.AlterField(
            model_name='fellowship_edit',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fellowship'),
        ),
        migrations.AlterField(
            model_name='fellowshipevent',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fellowship_event_covers'),
        ),
        migrations.AlterField(
            model_name='fellowshippost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fellowship_post_images/'),
        ),
    ]
