# Generated by Django 5.2.4 on 2025-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0009_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowship_edit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
