# Generated by Django 5.2.4 on 2025-08-28 10:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellowship', '0011_dailyverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowshippost',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fellowship_post_videos/'),
        ),
    ]
